Traceback (most recent call last):
  File "/home/denis/Documents/GitHub/server/oscilator_server/osci_local.py", line 330, in <module>
    osci(configs)
  File "/home/denis/Documents/GitHub/server/oscilator_server/osci_local.py", line 38, in osci
    CUDA = configs["cuda"]
KeyError: 'cuda'